site_name: HYDRAFloods Documentation
nav:
    - Overview: index.md
    - Installation: installation.md
    - Getting Started: getting-started.md
    - Using the Dataset class: using-datasets.md
    - Algorithms: algorithms.md
    - Workflow Example: workflow-example.md
    - Command Line Interface: cli.md
    - API Reference: 
        - datasets module: datasets.md
        - decorators module: decorators.md
        - geeutils module: geeutils.md
        - fetch module: fetch.md
        - filtering module: filtering.md
        - ml module: ml.md
        - thresholding module: thresholding.md
        - timeseries module: timeseries.md
        - utils module: utils.md
theme: 
    name: material
    logo: 'img/hydrafloods_logo.png'
    favicon: 'img/favicon.ico'
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - markdown.extensions.codehilite:
        guess_lang: false
plugins:
    - search
    - mkdocstrings
