name: docs
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings
      - run: pip install hydrafloods >= 0.2
      - run: mkdocs gh-deploy --force