name: unittests
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
          run: |
            pip install .
            pip install pytests
      - name: LOAD EE CREDENTIALS
          run: python ./.github/ee_token.py
          env:
            EARTHENGINE_TOKEN: ${{ secrets.EARTHENGINE_TOKEN }}
      - name: UNIT TESTS 
          run: |
            pytest